#!/usr/bin/env python
# This file is automatically generated by pywf script
# based on the content in pyproject.toml file

__version__ = "0.1.1"
__short_description__ = "An example project generated by cookiecutter-pywf_open_source."
__license__ = "MIT"
__author__ = "{{ cookiecutter.author }}"
__author_email__ = "{{ cookiecutter.author_email }}"
__maintainer__ = "{{ cookiecutter.author }}"
__maintainer_email__ = "{{ cookiecutter.author_email }}"

# run this script to print out the version number
if __name__ == "__main__":  # pragma: no cover
    print(__version__)
