#!/usr/bin/env python
# This file is automatically generated by pywf script
# based on the content in pyproject.toml file

__version__ = "0.1.1"
__short_description__ = "An example project generated by cookiecutter_pywf_open_source."
__license__ = "MIT"
__author__ = "Firstname Lastname"
__author_email__ = "firstname.lastname@email.com"
__maintainer__ = "Firstname Lastname"
__maintainer_email__ = "firstname.lastname@email.com"

# run this script to print out the version number
if __name__ == "__main__":  # pragma: no cover
    print(__version__)
